#!/bin/bash
#mpv ~/music/02.mp3
wget https://code.responsivevoice.org/getvoice.php?t=Hello\ World&tl=en-GB&sv=g1&vn=&pitch=0.5&rate=0.5&vol=1&gender=female\ voice
sleep 1s
mpv getvoice.php\?t\=Hello\ World
rm getvoice.php\?t\=Hello\ World

